/**
 * Turn the font masters in docs/assets/fonts/src/ into webfonts.
 *
 *   node scripts/build-fonts.mjs
 *
 * src/ holds licensed masters (git-ignored — the woff2 in the parent dir is what
 * ships). Each master is subset to Latin + the symbols the manual actually draws
 * on and written out as woff2, then fonts.css is regenerated from what landed, so
 * a @font-face never points at a file that does not exist.
 *
 * To add a font: drop the file in src/, add it to MANIFEST, run this.
 * Adding a weight of an existing family is the only common case.
 */
import { readdirSync, readFileSync, writeFileSync, unlinkSync, existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { join } from 'node:path';
import { spawnSync } from 'node:child_process';

const FONTS_DIR = fileURLToPath(new URL('../docs/assets/fonts/', import.meta.url));
const SRC_DIR = join(FONTS_DIR, 'src');
const CSS = join(FONTS_DIR, 'fonts.css');

// filename -> CSS family name. Explicit, because the masters disagree with
// themselves: Gullying's demo is internally named "Gullying Personal Use Only".
const MANIFEST = {
  'gullyingpersonaluseonlyreg-1jzrj.ttf': 'Gullying',
  'Gullying-Medium.otf': 'Gullying',
  'Gullying-SemiBold.otf': 'Gullying',
  'Gullying-Bold.otf': 'Gullying',
  'Bahnschrift.ttf': 'Bahnschrift',
  'GeistMono.ttf': 'Geist Mono',
};

// Latin, Latin Ext, punctuation, currency, arrows, math operators, geometric
// shapes — the dry-run traces and interview answers draw on all of these.
const UNICODES = [
  'U+0000-00FF', 'U+0131', 'U+0152-0153', 'U+02BB-02BC', 'U+02C6', 'U+02DA',
  'U+02DC', 'U+2000-206F', 'U+2074', 'U+20AC', 'U+2122', 'U+2190-21BB',
  'U+2212', 'U+2215', 'U+25A0-25FF', 'U+2605-2606', 'U+2713-2714', 'U+FEFF', 'U+FFFD',
].join(',');

const PYTHON = '/usr/bin/python3'; // the only interpreter here with fontTools + brotli

if (!existsSync(SRC_DIR)) {
  console.error(`no ${SRC_DIR} — nothing to build`);
  process.exit(0);
}

const masters = readdirSync(SRC_DIR).filter((f) => /\.(ttf|otf)$/i.test(f));
const unknown = masters.filter((f) => !MANIFEST[f]);
if (unknown.length) {
  console.error(`not in MANIFEST, refusing to guess a family name:\n  ${unknown.join('\n  ')}`);
  process.exit(1);
}

const faces = [];
for (const master of masters) {
  const family = MANIFEST[master];
  const out = master.replace(/\.(ttf|otf)$/i, '').replace(/[^A-Za-z0-9._-]/g, '-') + '.woff2';
  const res = spawnSync(PYTHON, [
    '-m', 'fontTools.subset',
    join(SRC_DIR, master),
    `--unicodes=${UNICODES}`,
    '--flavor=woff2',
    `--output-file=${join(FONTS_DIR, out)}`,
    '--no-hinting', '--desubroutinize', '--name-IDs=1,2,3,4,6',
  ], { encoding: 'utf8' });
  if (res.status !== 0) {
    console.error(`subset failed for ${master}:\n${res.stderr}`);
    process.exit(1);
  }

  // Weight/style come from the font, not the filename. Variable masters emit one
  // face covering their whole axis so a single file serves every weight.
  const probe = spawnSync(PYTHON, ['-c', `
import sys, json
from fontTools.ttLib import TTFont
f = TTFont(sys.argv[1], lazy=True)
os2 = f['OS/2']
italic = bool(os2.fsSelection & 1)
if 'fvar' in f:
    a = [a for a in f['fvar'].axes if a.axisTag == 'wght'][0]
    print(json.dumps({'weight': [a.minValue, a.maxValue], 'italic': italic}))
else:
    print(json.dumps({'weight': os2.usWeightClass, 'italic': italic}))
`, join(SRC_DIR, master)], { encoding: 'utf8' });
  if (probe.status !== 0) {
    console.error(`probe failed for ${master}:\n${probe.stderr}`);
    process.exit(1);
  }
  const { weight, italic } = JSON.parse(probe.stdout);
  const bytes = readFileSync(join(FONTS_DIR, out)).length;
  faces.push({ family, weight: Array.isArray(weight) ? weight.join(' ') : weight, italic, out, bytes, master });
}

// Drop last run's orphans so a removed master cannot leave a dangling @font-face.
const shipped = new Set(faces.map((f) => f.out));
for (const f of readdirSync(FONTS_DIR)) {
  if (f.endsWith('.woff2') && !shipped.has(f)) unlinkSync(join(FONTS_DIR, f));
}

writeFileSync(CSS, `/* Generated by scripts/build-fonts.mjs — do not edit. Run it instead. */
:root {
  /* Roles. Retired families: Space Grotesk (display), Inter (body),
     JetBrains Mono (mono). Declared here, not per page, so index.html and the
     standalone topic pages cannot drift apart. */
  --font-display: "Gullying", "Segoe UI", system-ui, sans-serif;
  --font-body: "Bahnschrift", "DIN Alternate", "Segoe UI", system-ui, sans-serif;
  --font-mono: "Geist Mono", ui-monospace, SFMono-Regular, monospace;
}

${faces.map((f) => `@font-face {
  font-family: "${f.family}";
  font-style: ${f.italic ? 'italic' : 'normal'};
  font-weight: ${f.weight};
  font-display: swap;
  src: url("${f.out}") format("woff2");
}`).join('\n\n')}
`);

for (const f of faces) {
  console.log(`${f.out.padEnd(34)} ${String(f.bytes).padStart(7)}B  ${f.family} ${f.weight}${f.italic ? ' italic' : ''}`);
}
console.log(`\n${faces.length} face(s) -> ${CSS}`);
