/**
 * Turn the font masters in docs/assets/fonts/src/ into webfonts.
 *
 *   node scripts/build-fonts.mjs
 *
 * src/ holds licensed masters (git-ignored — the woff2 in the parent dir is what
 * ships). Each master is subset to Latin + the symbols the manual actually draws
 * on and written out as woff2, then fonts.css is regenerated from what landed, so
 * a @font-face never points at a file that does not exist.
 *
 * The role vars live in the same generated file, so index.html and the standalone
 * topic pages cannot drift. Empty src/ is the normal state: the portal ships the
 * Google Fonts stack, and this script exists so swapping in a self-hosted family
 * is a file drop rather than a CSS edit.
 *
 * To add a font: drop the file in src/, add it to MANIFEST, run this, then point
 * the role you want at the new family in the :root block below.
 */
import { readdirSync, readFileSync, writeFileSync, unlinkSync, existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { join } from 'node:path';
import { spawnSync } from 'node:child_process';

const FONTS_DIR = fileURLToPath(new URL('../docs/assets/fonts/', import.meta.url));
const SRC_DIR = join(FONTS_DIR, 'src');
const CSS = join(FONTS_DIR, 'fonts.css');

// Roles as they stand. Editing this block IS the font change; everything else in
// the portal reads these three vars.
const ROLES = `  --font-display: "Space Grotesk", Inter, system-ui, sans-serif;
  --font-body: Inter, system-ui, sans-serif;
  --font-mono: "JetBrains Mono", ui-monospace, monospace;`;

// filename -> CSS family name. Explicit, because masters disagree with
// themselves: a foundry's demo build is often internally named differently from
// the family you asked for. Keyed on the filename so the shipped name is a
// decision, not something inherited from a name table.
const MANIFEST = {
  'Bahnschrift.ttf': 'Bahnschrift',
  'GeistMono.ttf': 'Geist Mono',
  'Gullying-Regular.otf': 'Gullying',
  'Gullying-Medium.otf': 'Gullying',
  'Gullying-SemiBold.otf': 'Gullying',
  'Gullying-Bold.otf': 'Gullying',
};

// Latin, Latin Ext, punctuation, currency, arrows, math operators, geometric
// shapes — the dry-run traces and interview answers draw on all of these.
const UNICODES = [
  'U+0000-00FF', 'U+0131', 'U+0152-0153', 'U+02BB-02BC', 'U+02C6', 'U+02DA',
  'U+02DC', 'U+2000-206F', 'U+2074', 'U+20AC', 'U+2122', 'U+2190-21BB',
  'U+2212', 'U+2215', 'U+25A0-25FF', 'U+2605-2606', 'U+2713-2714', 'U+FEFF', 'U+FFFD',
].join(',');

const PYTHON = '/usr/bin/python3'; // the only interpreter here with fontTools + brotli

// Empty src/ is the normal state: the portal ships the Google Fonts stack and this
// script exists so dropping in a self-hosted family is a file copy, not a CSS edit.
const render = (faces) => `/* Generated by scripts/build-fonts.mjs — do not edit. Run it instead.
 *
 * The portal resolves type through the three role vars below; every page reads
 * them instead of naming a family, so changing the theme is an edit to ROLES in
 * scripts/build-fonts.mjs rather than a sweep through the stylesheets. The theme in
 * use is the original Google Fonts stack — any face declared further down is staged
 * here and only takes effect once a role points at it.
 */
:root {
${ROLES}
}
${faces.length ? '\n' + faces.map((f) => `@font-face {
  font-family: "${f.family}";
  font-style: ${f.italic ? 'italic' : 'normal'};
  font-weight: ${f.weight};
  font-display: swap;
  src: url("${f.out}") format("woff2");
}`).join('\n\n') + '\n' : ''}`;

if (!existsSync(SRC_DIR)) {
  writeFileSync(CSS, render([]));
  console.log(`${CSS} rewritten (0 faces — no src/ dir)`);
  process.exit(0);
}

const masters = readdirSync(SRC_DIR).filter((f) => /\.(ttf|otf)$/i.test(f));
const unknown = masters.filter((f) => !MANIFEST[f]);
if (unknown.length) {
  console.error(`not in MANIFEST, refusing to guess a family name:\n  ${unknown.join('\n  ')}`);
  process.exit(1);
}

const faces = [];
for (const master of masters) {
  const family = MANIFEST[master];
  const out = master.replace(/\.(ttf|otf)$/i, '').replace(/[^A-Za-z0-9._-]/g, '-') + '.woff2';
  const res = spawnSync(PYTHON, [
    '-m', 'fontTools.subset',
    join(SRC_DIR, master),
    `--unicodes=${UNICODES}`,
    '--flavor=woff2',
    `--output-file=${join(FONTS_DIR, out)}`,
    '--no-hinting', '--desubroutinize', '--name-IDs=1,2,3,4,6',
  ], { encoding: 'utf8' });
  if (res.status !== 0) {
    console.error(`subset failed for ${master}:\n${res.stderr}`);
    process.exit(1);
  }

  // Weight/style come from the font, not the filename. Variable masters emit one
  // face covering their whole axis so a single file serves every weight.
  const probe = spawnSync(PYTHON, ['-c', `
import sys, json
from fontTools.ttLib import TTFont
f = TTFont(sys.argv[1], lazy=True)
os2 = f['OS/2']
italic = bool(os2.fsSelection & 1)
if 'fvar' in f:
    a = [a for a in f['fvar'].axes if a.axisTag == 'wght'][0]
    print(json.dumps({'weight': [a.minValue, a.maxValue], 'italic': italic}))
else:
    print(json.dumps({'weight': os2.usWeightClass, 'italic': italic}))
`, join(SRC_DIR, master)], { encoding: 'utf8' });
  if (probe.status !== 0) {
    console.error(`probe failed for ${master}:\n${probe.stderr}`);
    process.exit(1);
  }
  const { weight, italic } = JSON.parse(probe.stdout);
  const bytes = readFileSync(join(FONTS_DIR, out)).length;
  faces.push({ family, weight: Array.isArray(weight) ? weight.join(' ') : weight, italic, out, bytes, master });
}

// Drop last run's orphans so a removed master cannot leave a dangling @font-face.
const shipped = new Set(faces.map((f) => f.out));
for (const f of readdirSync(FONTS_DIR)) {
  if (f.endsWith('.woff2') && !shipped.has(f)) unlinkSync(join(FONTS_DIR, f));
}

writeFileSync(CSS, render(faces));

for (const f of faces) {
  console.log(`${f.out.padEnd(34)} ${String(f.bytes).padStart(7)}B  ${f.family} ${f.weight}${f.italic ? ' italic' : ''}`);
}
console.log(`\n${faces.length} face(s) -> ${CSS}`);
